GSW as a service
RIT-Launch-Initiative/GSW pull request #11
Opened 2024-10-01 19:39 UTC by ZZwatermelon

A script which creates a .service file, enabling GSW to be run as a service

2024-10-02 20:39 UTC, AarC10 commented
![image](https://github.com/user-attachments/assets/58e9cc07-2119-496f-9764-292f4964d9ac)

?

2024-10-02 20:45 UTC, AarC10 commented
Nvm. Figured out why. Maybe add to the README for setting this up. Need to test further too btw. I see it has the correct perms now, but when running mem_view, it still complains about failing to open file, and I cant run sims atm

2024-10-02 21:28 UTC, ZZwatermelon commented
>  when running mem_view, it still complains about failing to open file
I believe I fixed this

2024-10-03 02:38 UTC, AarC10 commented
Awesome! That seems better. Only comments are to update the README with instructions for setting it up as a service and  I'll approve it for merging

2024-10-05 15:17 UTC, AarC10 requested changes

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +If you want the sevrice to run on startup:
Typo here

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +## Create Service Script (for linux)
Capitalize Linux

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +sudo systemctl start gsw
```suggestion
`sudo systemctl start gsw`
```

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +sudo systemctl stop gsw
```suggestion
`sudo systemctl stop gsw`
```

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +sudo systemctl enable gsw
```suggestion
`sudo systemctl enable gsw`
```

2024-10-05 15:17 UTC, AarC10 commented on README.md
> +### Running the Service
Should also include that you can check the status of gsw by doing
`sudo systemctl status gsw`

2024-10-05 15:39 UTC, AarC10 approved these changes

2024-10-05 15:39 UTC, AarC10 commented
MURGE

2024-10-08 01:38 UTC, merged